# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: uwusca
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: desafio-embarca
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-challenge

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    BUCKET_NAME: bucket-serverless-challenge
    DB_HOST: 'sqllambda.cfiikuwkal2n.us-east-1.rds.amazonaws.com'
    DB_USER: 'ServerlessAccount'
    DB_PASSWORD: 'admin1234'
    DB_NAME: 'sqllambda'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - "arn:aws:s3:::bucket-serverless-challenge/*"

functions:
  lambda1:
    name: downloadCSVs
    handler: lambda1.handler
    description: download-csvs
    timeout: 30
    memorySize: 128
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
        - "links.yml"
    events:
      - http:
          path: download
          method: post
  lambda2:
    name: processCSVs
    handler: lambda2.handler
    description: process-csvs
    timeout: 30
    memorySize: 128
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
        - .
    events:
      - http:
          path: process
          method: post

stepFunctions:
  stateMachines:
    processCSVStateMachine:
      name: processCSVStateMachine
      definition:
        Comment: "Processing CSVs"
        StartAt: DownloadCSVs
        States:
          DownloadCSVs:
            Type: Task
            Resource: 'arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-downloadCSVs'
            Next: processCSVs
          ProcessCSVData:
            Type: Task
            Resource: 'arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:${self:service}-${self:provider.stage}-processCSVs'
            End: true

plugins:
  - serverless-python-requirements

package:
  individually: true